"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# --- TUNING DE RENDIMIENTO SAP SYNC ---
# Si la variable no existe en el .env, toma un valor por defecto seguro.

SAP_MAX_WORKERS_DEFAULT = int(os.environ.get("SAP_MAX_WORKERS_DEFAULT", 4))
SAP_MAX_WORKERS_HEAVY = int(os.environ.get("SAP_MAX_WORKERS_HEAVY", 8))

DB_BATCH_SIZE_LARGE = int(os.environ.get("DB_BATCH_SIZE_LARGE", 2000))
DB_BATCH_SIZE_MEDIUM = int(os.environ.get("DB_BATCH_SIZE_MEDIUM", 1000))

ODATA_CHUNK_SIZE = int(os.environ.get("ODATA_CHUNK_SIZE", 50))

# --- CONFIGURACIÓN SAP ---
SAP_USERNAME = env("SAP_USERNAME")
SAP_PASSWORD = env("SAP_PASSWORD")
SAP_AMBIENTE = env("SAP_AMBIENTE")
SAP_URL = env("SAP_URL")
SAP_PORT = env("SAP_PORT")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l!d!z*h6yj#omjj-$@qi303sfe3s&$t+=5ew&uch6y(1+cx$45"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "huey.contrib.djhuey",
    "users",
    "core",
    "sap_sync",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {"default": env.db("DATABASE_URL")}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# --- CONFIGURACIÓN DE HUEY (WORKER) ---
HUEY = {
    # 1. El motor: Usamos SQLite local solo para la cola de mensajes
    "huey_class": "huey.SqliteHuey",
    "name": "sap_worker_queue",
    "filename": os.path.join(BASE_DIR, "huey_tasks.sqlite3"),
    "immediate": False,
    "results": True,
    "store_none": False,
    # 3. Configuración del Consumer
    "consumer": {
        "workers": 4,
        "worker_type": "thread",
        "initial_delay": 0.1,
        "backoff": 1.15,
        "max_delay": 10.0,
        "scheduler_interval": 1,
        "periodic": True,
        "check_worker_health": True,
        "health_check_interval": 5,
    },
}
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "huey": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "sap_sync": {  # Para los loggers dentro de tu tasks.py
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
